@startuml 1.2 User logs in (server side)
title 1.2 User logs in (server side)

actor "Client" as client
box "Server App" #LightGreen
    participant "Communication" as com
    participant "Data" as data
end box
actor "Connected Clients" as connected

client->>com++: USER_CONNECT (User)
com->data++: addUser (UserLite)
return void | Exception
com->>connected: USER_CONNECT (User)
com->>client: USER_CONNECTED (List<UserLite>)

@enduml