@startuml 1.2 User logs in (client)
title 1.2 User logs in (client)

actor "User" as user
box "Client App" #LightBlue
    participant "HMI" as hmi
    participant "Data" as data
    participant "Communication" as com
end box
actor "Server" as server

opt Create new profile 
    alt Profile file exists
        user ->> hmi++: Click on "Import profile"
        hmi -> data++: importProfile(filePath: str)
        return status: bool
        deactivate hmi 
    else Profile file doesn't exist
        user ->> hmi++: Click on "Create profile"
        hmi -> data++: createProfile(newClient: Client)
        return status: bool
        deactivate hmi
    end
end



user ->> hmi++: Click on "Login"
hmi -> data++: checkCredentials(user: str, pw: str)
return valid : boolean

opt credentials are correct
    hmi -> com++ : connect(User, List<Track>)
    com->>server: USER_CONNECT (User)
    return void | NetworkException

    deactivate hmi

    server ->> com++: USER_CONNECTED (List<UserLite>)
    deactivate server
    com->data++: setConnectedUsers(List<UserLite>)
    data->>hmi : NEW_USERS()
    return void
    deactivate com
end

@enduml