@startuml 1.2 User logs in (client)
actor NewClient

box Client App #LightBlue
    participant HMIMain as HMI
    participant Data
    participant Communication
end box

actor Server 

opt Create new profile 
    alt Profile file exists
        NewClient ->> HMI++: Click on "Import profile"
        HMI -> Data++: importProfile(filePath: str)
        return status: bool
        deactivate HMI 
    else Profile file doesn't exist
        NewClient ->> HMI++: Click on "Create profile"
        HMI -> Data++: createProfile(newClient: Client)
        return status: bool
        deactivate HMI
    end
end



NewClient ->> HMI++: Click on "Login"
HMI -> Data++: checkCredentials(user: str, pw: str)
return valid : boolean

opt credentials correct
    HMI -> Communication++ : connect(User, List<Track>)
    Communication->>Server: USER_CONNECT (User)
    return void | NetworkException
end

deactivate HMI

opt Credentials are correct
    Server ->> Communication++: USER_CONNECTED (List<UserLite>)
    deactivate Server
    Communication->Data++: setConnectedUsers(List<UserLite>)
    Data->>HMI : NEW_USERS()
    return void
    deactivate Communication
end

@enduml