@startuml 1.2 User logs in (connected clients side)
title 1.2 User logs in (connected clients side)

actor "Server" as server
box "Client application" #LightYellow
    participant "Communication" as com
    participant "Data" as data
    participant "HMI" as hmi
end box

@enduml