@startuml 1.4 User export his profile to a file (client side)
title 1.4 User export his profile to a file (client side)

actor "User" as user

box "Client App" #LightBlue
    participant "HMIMain" as hmi
    participant "Data" as data
end box

user ->> hmi++ : Click on "Export profile"

hmi -> data++ : exportProfile(filePath : str)
return void | Exception

deactivate hmi

@enduml