@startuml 1.6 User edits his profile (client side)
title 1.6 User edits his profile (client side)

actor "User" as user
box "Client App" #LightBlue
    participant "HMI" as hmi
    participant "Data" as data
    participant "Communication" as com
end box
actor "Server" as server

user ->> hmi++: Click on "Save changes"
hmi->data++: editUser(User)
data->>hmi++: UPDATE_USER(User)
hmi->com++: editUser(User)
com->>server: USER_UPDATE (User)
deactivate hmi
deactivate com
return void | Exception
@enduml
