@startuml 1.7 User disconnects (client side)

actor "User" as user
box "Client App" #LightBlue
    participant "HMI" as hmi
    participant "Data" as data
    participant "Communication" as com
end box
actor "Server" as server

@enduml