@startuml 1.7 User disconnects (server side)

actor "Client" as client
box "Server App" #LightGreen
    participant "Communication" as com
    participant "Data" as data
end box
actor "Connected Clients" as connected

@enduml