@startuml 2.1 User add a music to his local library from a local file (client side)
title 2.1 User add a music to his local library from a local file (client side)

actor "User" as user
box "Client App" #LightBlue
    participant "HMI" as hmi
    participant "Data" as data
end box

user ->> hmi : Adding a track to the local library
activate hmi

hmi -> data : save(Track)
activate data

data --> hmi : void | Exception
deactivate data
deactivate hmi

@enduml