@startuml Download Track (server side)
actor "User requesting the file" as User1
box Server
    participant Communication
    participant Data
end box
actor "User owning the file" as User2

User1 ->> Communication : download(TrackLite)
activate Communication

Communication -> Data : getOwner(TrackLite)
activate Data

Data --> Communication : UserLite | Exception
deactivate Data

Communication ->> User2 : requestAudioFile(UserLite, TrackLite)
deactivate Communication
activate User2

User2 -->> Communication : Track | Exception
deactivate User2
activate Communication

Communication ->> User1 : saveAudioFile(Track)
deactivate Communication

@enduml