@startuml Download Music (client side)
actor User
participant "IHM Music" as IHM
participant Data
participant Communication
actor Server

User ->> IHM : Click on "Download"
activate IHM

IHM -> Data : addToLibrary(Music)
activate Data

Data -> Communication : downloadMusic(Music)
activate Communication
Communication ->> Server : downloadMusic(Music)
activate Server
Communication --> Data : void | Exception
deactivate Communication

Data --> IHM : void | Exception
deactivate Data
deactivate IHM

Server ->> Communication : saveFileAndLinkToMusic(Music, File)
deactivate Server
activate Communication
Communication -> Data : saveFileAndLinkToMusic(Music, File)
activate Data

Data -> IHM : updateDisplay()
activate IHM
IHM --> Data : void
deactivate IHM

Data --> Communication : void | Exception
deactivate Data
deactivate Communication

@enduml