@startuml Download Music (client side)
actor User
participant "IHM Music" as IHM
participant Data
participant Communication
actor Server

User ->> IHM : Click on "Download"
activate IHM

IHM -> Data : addToLibrary(TrackLite)
activate Data

Data -> Communication : download(TrackLite)
activate Communication
Communication ->> Server : download(TrackLite)
activate Server
Communication --> Data : void | Exception
deactivate Communication

Data --> IHM : void | Exception
deactivate Data
deactivate IHM

Server ->> Communication : saveAudioFile(Track)
deactivate Server
activate Communication
Communication -> Data : saveAudioFile(Track)
activate Data

Data -> IHM : updateDisplay()
activate IHM
IHM --> Data : void
deactivate IHM

Data --> Communication : void | Exception
deactivate Data
deactivate Communication

@enduml