@startuml Edit Track (client side)
actor User
participant "IHM Music" as IHM
participant Data
participant Communication
actor Server

User ->> IHM : Enregistrer une fiche musique
activate IHM

IHM -> Data : save(Track)
activate Data

opt Track is public
    Data -> Communication : updateTrack(TrackLite)
    activate Communication
    Communication ->> Server : updateTrack(TrackLite)
    activate Server
    Communication --> Data : void | Exception
    deactivate Communication
end

Data --> IHM : void
deactivate Data
deactivate IHM


note across: The sequence below concerns any other users
Server ->> Communication : updateTrack(TrackLite)
deactivate Server
activate Communication
Communication -> Data : updateTrack(TrackLite)
activate Data
Data --> Communication : void
deactivate Data
deactivate Communication

@enduml