@startuml 2.3 User edit the music file information (server side)
title 2.3 User edit the music file information (server side)

actor "Client" as client
box "Server App" #LightGreen
    participant "Communication" as com
    participant "Data" as data
end box
actor "Connected Clients" as connected

opt 
    client ->> com++:  UPDATE_TRACK (TrackLite) 
    com -> data++: updateTrack(TrackLite)
    return void | Exception
    com->>connected: UPDATE_TRACK (TrackLite) 
    deactivate com
end

opt 
    client ->> com++:  PUBLISH_TRACK (TrackLite) 
    com -> data++: publishTrack(TrackLite)
    return void | Exception
    com->>connected: PUBLISH_TRACK (TrackLite) 
    deactivate com
end

opt 
    client ->> com++:  UNPUBLISH_TRACK (TrackLite) 
    com -> data++: unpublishTrack(TrackLite)
    return void | Exception
    com->>connected: UNPUBLISH_TRACK (TrackLite) 
    deactivate com
end
@enduml