@startuml Edit Visibility (server side)
actor Client
box Server
    participant Communication
    participant Data
end box
actor "Other clients" as Clients

Client ->> Communication : changeVisibility(TrackLite)
activate Communication

Communication -> Data : updateVisibility(TrackLite)
activate Data

Data --> Communication : void | Exception
deactivate Data

Communication ->> Clients : changeVisibility(TrackLite)
deactivate Communication
activate Clients

@enduml