@startuml 3.1 User select a track to start listening (client side)
title 3.1 User select a track to start listening (client side)

actor "User" as user
box "Client App" #LightBlue
    participant "HMIMusic" as hmi
    participant "Data" as data
    participant "Communication" as com
end box
actor "Server" as server

alt Track on the local database
    user ->> hmi++: Click "listen"
    hmi -> data++: downloadTrack(uuid : UUID)
    data->>hmi: DOWNLOADED_TRACK (Track)
    return void | Exception
    deactivate hmi

else Track not on the local database 
    user ->> hmi++: Click "listen"

    hmi -> com++: downloadTrack(UUID)
    com ->> server: GET_TRACK (UUID)
    return void | Exception
    deactivate hmi

    server ->> com++: DOWNLOAD_TRACK (Track) 
    com -> data++: updateTrack(Track)
    data->>hmi++: TRACK_READY_PLAY (Track) 
    data-->com: void | Exception
end 

@enduml



