@startuml 3.1 User select a track to start listening (client)
title 3.1 User select a track to start listening (client)

actor "User" as user
box "Client App" #LightBlue
    participant "HMI" as hmi
    participant "Data" as data
    participant "Communication" as com
end box
actor "Server" as server

user ->> hmi++: Select a track


alt Track on the local database
    hmi -> data++: downloadTrack(uuid : UUID)
    data->>hmi: DOWNLOADED_TRACK (Track)
    return void | Exception

else Track not on the local database 
    hmi -> data++: downloadTrack(uuid : UUID)
    data -> com++: downloadTrack(uuid : UUID)
    com ->> server++: GET_TRACK (UUID)
    com --> data: void | Exception
    deactivate data
    deactivate com

    server ->> com++: DOWNLOAD_TRACK (Track) 
    com -> data++: updateTrack(track : Track)
    data->>hmi: DOWNLOADED_TRACK (Track) 
end 

@enduml



