@startuml 3.2 User pause a music (user side)
title 3.2 User pause a music (user side)

actor "User" as user
box "Client App" #LightBlue
    participant "HMI" as hmi
    participant "Data" as data
end box

user ->> hmi : Click on pause Music
activate hmi

hmi -> data : pauseMusic()
activate data
return void | Exception
deactivate data
deactivate hmi

@enduml
