@startuml 4.1 User add a rating to a music (server side)
title 4.1 User add a rating to a music (server side)

actor "Client" as client
box "Server App" #LightGreen
    participant "Communication" as com
    participant "Data" as data
end box
actor "Connected Clients" as connected

client ->> com : PUBLISH_RATING (UUID, Rating)

activate com

com -> data++ : getTrack(trackId : UUID)
note right : Notes are not stored on the server's RAM 
return Track | Exception

alt track exists
    com ->> connected : PUBLISH_RATING (UUID, Rating)
end

deactivate com

@enduml