@startuml 4.1 User add a rating to a music (user side)
title 4.1 User add a rating to a music (user side)

actor "User" as user
box "Client App" #LightBlue
    participant "HMIMusic" as hmi
    participant "Data" as data
    participant "Communication" as com
end box
actor "Server" as server

user ->> hmi++: Add Rating

hmi -> data++ : getPlayedTrack()
return track : Track


hmi -> data++ : addRating(trackId : UUID, rating : Rating)
alt track owned
    data->data++: saveTrackFile(trackId : UUID)
    return void | Exception
end

deactivate hmi
data->>hmi++:  NEW_RATING (Rating) 
deactivate data 

alt track not owned
    hmi -> com++ : addRating(trackId : UUID, rating : Rating)
    com ->> server : PUBLISH_RATING (Rating)
    return void | NetworkException
end


@enduml