@startuml 4.1 User add a rating to a music (server)

actor Client as client

box "Server App" #LightBlue
    participant Communication as com
    participant Data as data
end box

actor TrackOwner as owner

client ->> com : addRating(trackId : UUID, rating : Rating)

activate com

com -> data++ : getMusic(trackId : UUID)
note right : Les notes ne sont pas stockées.
return track : Track

alt track exists
    com ->> owner : addRating(trackId : UUID, rating : Rating)
else track not exists
    com ->> client : TrackNotFound
end

deactivate com

@enduml