@startuml 4.1. User add a rating to a music (client - sender)

actor Client as client

box "Client App" #LightBlue
    participant IHMMusic as ihm
    participant Data as data
    participant Communication as com
end box

actor Server as server

client ->> ihm : Add Rating

ihm -> data++ : addRating(musicId : UUID, rating : Rating)
activate ihm

alt owning music
    data -> data++ : saveRating(musicId : UUID, rating : Rating)
    return void | RatingException
else not owning music
    data -> com++ : addRating(musicId : UUID, rating : Rating)
    com ->> server : addRating(musicId : UUID, rating : Rating)
    return void | NetworkException
end

return void | Exception
deactivate ihm

@enduml