@startuml 4.1. User add a rating to a music (client - sender)

actor Client as client

box "Client App" #LightBlue
    participant IHMMusic as ihm
    participant Data as data
    participant Communication as com
end box

actor Server as server

client ->> ihm : Add Rating

ihm -> data++ : getTrack(trackId : UUID)
return track : Track

alt track owned
    ihm -> data++ : addRating(trackId : UUID, rating : Rating)
    data -> data++ : saveRating(trackId : UUID, rating : Rating)
    return void | RatingException
    return void | RatingException
else track not owned
    ihm -> com++ : addRating(trackId : UUID, rating : Rating)
    com ->> server : addRating(trackId : UUID, rating : Rating)
    return void | NetworkException
end

deactivate ihm

@enduml