@startuml 4.2 User add a comment to a music (connected clients side)

actor Server as server

box "Client App" #LightBlue
    participant Communication as com
    participant Data as data
end box

server ->> com : PUBLISH_COMMENT (UUID, Comment)

activate com
com -> data++ : addComment(trackId : UUID, rating : Comment)

alt track owned
    data->data++: saveTrackFile(trackId : UUID)
    return void | Exception
end

return void

@enduml