@startuml 4.2. User add a comment to a music (server)

actor Client as client

box "Client App" #LightBlue
    participant Communication as com
    participant Data as data
end box

actor TrackOwner as owner

client ->> com : addComment(trackId : UUID, comment : Comment)

activate com

com -> data++ : getTrack(TrackId : UUID)
note right : Les commentaires ne sont pas stockés.
return track : Track

alt track exists
    com ->> owner : addComment(trackId : UUID, comment : Comment)
else music not exists
    com ->> client : TrackNotFound
end

deactivate com

@enduml