@startuml 4.2. User add a comment to a music (client - sender)

actor Client as client

box "Client App" #LightBlue
    participant IHMMusic as ihm
    participant Data as data
    participant Communication as com
end box

actor Server as server

client ->> ihm : Add Rating

ihm -> data++ : getTrack(trackId : UUID)
return track : Track

alt track owned
    ihm -> data++ : addComment(trackId : UUID, comment : Comment)
    data -> data++ : saveComment(trackId : UUID, comment : Comment)
    return void | CommentException
    return void | CommentException
else track not owned
    ihm -> com++ : addComment(trackId : UUID, comment : Comment)
    com ->> server : addComment(trackId : UUID, comment : Comment)
    return void | NetworkException
end

deactivate ihm

@enduml