@startuml 4.2. User add a comment to a music (client - sender)

actor Client as client

box "Client App" #LightBlue
    participant IHMMusic as ihm
    participant Data as data
    participant Communication as com
end box

actor Server as server

client ->> ihm : Add Comment

ihm -> data++ : addComment(musicId : UUID, comment : Comment)
activate ihm

alt owning music
    data -> data++ : saveComment(musicId : UUID, comment : Comment)
    return void | CommentException
else not owning music
    data -> com++ : addComment(musicId : UUID, comment : Comment)
    com ->> server : addComment(musicId : UUID, comment : Comment)
    return void | NetworkException
end

return void | Exception
deactivate ihm

@enduml