@startuml 4.2. User add a comment to a music (server)

actor Client as client

box "Client App" #LightBlue
    participant Communication as com
    participant Data as data
end box

actor TrackOwner as owner

client ->> com : addComment(musicId : UUID, comment : Comment)

activate com

com -> data++ : getMusic(musicId : UUID) : Music
return Music

alt music exists
    com ->> owner : addComment(musicId : UUID, comment : Comment)
else music not exists
    com ->> client : MusicNotFound
end

deactivate com

@enduml