@startuml 5.1 Server is started (server side)
title 5.1 Server is started (server side)

actor "Admin" as admin
box "Server App" #LightGreen
    participant "Main" as main
    participant "Communication" as com
    participant "Data" as data
end box

admin ->> main : Start server
activate main

create com
main -> com++ : new()
return object : Communication

create data
main -> data++ : new()
return object : Data

main -> com++ : setData(data : Data)
return void

main -> data++ : setCommunication(com : Communication)
return void

main -> com++ : startServer(port : int)
return void | ServerOpenException

deactivate main

@enduml
