@startuml 5.1 Server is started (server side)
title 5.1 Server is started (server side)

actor "Admin" as admin
box "Server App" #LightGreen
    participant "HMI" as hmi
    participant "Communication" as com
    participant "Data" as data
end box

admin ->> hmi : Start server
activate hmi

create com
hmi -> com++ : new()
return object : Communication

create data
hmi -> data++ : new()
return object : Data

hmi -> com++ : setData(data : Data)
return void

hmi -> data++ : setCommunication(com : Communication)
return void

hmi -> com++ : startServer(port : int)
return void | ServerOpenException

deactivate hmi

@enduml
