@startuml Server is stopped (server side)

actor Admin as admin

box "Server App" #LightBlue
    participant IHMServer as ihm
    participant Communication as com
end box

actor ConnectedClient as client

admin ->> ihm : Stop server
note left : Aucun module IHMServer n'est défini. Cependant, \nil serait étrange que "Administrateur" envoie \ndirectement un message à "Communication, d'où \nune IHM (ex: console).
activate ihm

ihm -> com++ : stopServer()

com -> com++ : getUserSockets()
return sockets : Map<UUID, Socket>

loop <uuid, socket> of sockets
    com -> client : serverClose()
end

return void

deactivate ihm

@enduml
