@startuml Client Connect
actor NewClient

box Client App #LightBlue
    participant IHMMain as IHM
    participant Data
    participant Communication
end box

actor Server 

opt Create new profile 
    alt Profile file exists
        NewClient ->> IHM++: Click on "Import profile"
        IHM -> Data++: importProfile(file: strPath)
        return status: bool
        deactivate IHM 
    else Profile file doesn't exist
        NewClient ->> IHM++: Click on "Create profile"
        IHM -> Data++: createProfile(newClient: Client)
        return status: bool
        deactivate IHM
    end
end



NewClient ->> IHM++: Click on "Login"
IHM -> Data++: checkCredentials(user: str, pw: str)
return valid : boolean

opt credentials correct
    IHM -> Communication++ : connect(user : UserLite, tracks : List<TrackLite>)
    Communication->>Server: connect(user : UserLite, tracks : List<TrackLite>)
    return void | NetworkException
end

deactivate IHM

opt Credentials are correct
    Server ->> Communication++: updateData(users : List<UserLite>, tracks : List<TrackLite>)
    deactivate Server
    Communication->Data++: updateData(users : List<UserLite>, tracks : List<TrackLite>)
    Data->>IHM : updateData(users : List<UserLite>, tracks : List<TrackLite>)
    return void
    deactivate Communication
end

@enduml
