@startuml Communication module class diagram
title Communication module class diagram

package server {
  class ServerCommunicationController {
    Model model
    void onMessage(SocketMessage, ClientHandler)
  }

  class ClientHandler {
    Socket socket
    ObjectInputStream input
    ObjectOutputStream output
  }

  class RequestHandler {
    void sendAllExclude(SocketMessage, UUID)

    void userConnect(SocketMessage, UserLite, ClientHandler)
    void userDisconnect(SocketMessage, UserLite, ClientHandler)
    void userEdit(SocketMessage, UserLite, ClientHandler)
    void publishTrack(SocketMessage, TrackLite, ClientHandler)
    void ...()
  }


}

package client {
  class ClientCommunicationController
  class ClientCommunication
  class ClientMessageListener
  class ClientMessageWriter
  class MainViewServicesImp
  class MusicViewServicesImp
  interface MainViewServices
  interface MusicViewServices
}






class ClientCommunicationController {
  ClientCommunication c
  IHMMainCallsCommImp iIHMMain
  IHMMusicCallsCommImp iIHMMusic
}

class ClientCommunication {
  Socket socket
  ClientMessageListener listener
  ClientMessageWriter writer
}

class ClientMessageListener {
  Socket socket
  ObjectInputStream input
  ObjectOutputStream output
  ClientCommunication client
}

class ClientMessageWriter {
  Socket socket
  ObjectOutputStream output
  ClientCommunication client
}


interface MainViewServices {
  connect(User, List<Track>)
  editUser(User)
  disconnect(User)
}

interface MusicViewServices {
  downloadTrack(UUID)
  updateTrack(UUID)
  publishTrack(UUID)
  unpublishTrack(UUID)
  addRating(UUID, Rating)
  addComment(UUID, Comment)
}

class MainViewServicesImp implements MainViewServices {

}

class MusicViewServicesImp implements MusicViewServices {

}

ServerCommunicationController "1" -- "0..*" ClientHandler
ServerCommunicationController "-requestHandler" o-- "  1" RequestHandler
RequestHandler "0..*" <-right- "-users" ClientHandler

ClientCommunicationController o-- ClientCommunication
ClientCommunicationController o-- MainViewServicesImp
ClientCommunicationController o-- MusicViewServicesImp
ClientCommunication o-- "0..1" ClientMessageListener
ClientCommunication o-- "0..1" ClientMessageWriter
@enduml

