@startuml Data server class diagram
title Data server class diagram


    interface DataUserServices {
        getUser(UUID) : UserLite | Exception
        addUser(UserLite) : void | Exception
        deleteUser(UserLite) : void | Exception
        updateUser(UserLite) : void | Exception
    }

    interface DataTrackServices {
        updateTrack(TrackLite) : void | Exception
        getTrack(UUID) : Track | Exception
        removeAllTracks(UserUUID) : void | Exception
    }

    class DataUserServicesImpl implements DataUserServices {

    }

    class DataTrackServicesImpl implements DataTrackServices {

    }

    class ServerController{
        dataRepository : DataRepository
        dataUserServicesImpl : DataUserServicesImpl
        dataTrackServicesImpl : DataTrackServicesImpl
    }

    class DataRepository {
        connectedUsers : Map<UserLite, List<TrackLite>
        tracks : List<TrackLite>
    }

    DataRepository --o ServerController
    DataUserServicesImpl --o ServerController
    DataTrackServicesImpl --o ServerController
    
@enduml